# Generated by Django 3.2 on 2021-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=30, verbose_name='邮件')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号')),
                ('edu', models.CharField(max_length=10, verbose_name='学历')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('title', models.CharField(max_length=20, verbose_name='职称')),
                ('skill', models.CharField(max_length=20, verbose_name='技能')),
                ('exp', models.CharField(max_length=20, verbose_name='经验')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10, verbose_name='性别')),
                ('address', models.CharField(max_length=60, verbose_name='地址')),
                ('image', models.FileField(default='/avatars/default.jpg', upload_to='static/avatars/', verbose_name='头像')),
            ],
        ),
    ]
