# Generated by Django 3.2 on 2021-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_information', '0002_auto_20210501_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='await',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
