# Generated by Django 3.2 on 2021-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=80, verbose_name='要求标签')),
                ('english', models.CharField(max_length=20, null=True, verbose_name='英语等级')),
                ('job_info', models.TextField(verbose_name='岗位详情')),
                ('address', models.CharField(max_length=30, verbose_name='上班地址')),
                ('release', models.CharField(max_length=20, verbose_name='发布时间')),
                ('cp_nature', models.CharField(max_length=20, verbose_name='公司性质')),
                ('cp_scale', models.CharField(max_length=60, null=True, verbose_name='公司规模')),
                ('cp_industry', models.CharField(max_length=20, null=True, verbose_name='公司行业')),
                ('cp_info', models.TextField(blank=True, verbose_name='公司介绍')),
            ],
        ),
    ]
