# Generated by Django 3.2 on 2021-05-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Detail_job_info', '0001_initial'),
        ('Job_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='job_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Job_information.work'),
        ),
    ]
