# Generated by Django 3.2 on 2021-05-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reptile_task', '0003_rename_position_text_run_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, verbose_name='职位名称')),
                ('salary', models.CharField(max_length=20, verbose_name='工作薪资')),
                ('city', models.CharField(max_length=20, verbose_name='工作城市')),
                ('exp', models.CharField(max_length=20, null=True, verbose_name='经验')),
                ('edu', models.CharField(max_length=10, null=True, verbose_name='学历')),
                ('job_num', models.CharField(max_length=20, null=True, verbose_name='招聘人数')),
                ('company', models.CharField(max_length=60, verbose_name='公司名称')),
                ('welfare', models.CharField(max_length=100, null=True, verbose_name='福利')),
                ('job_url', models.CharField(max_length=120, verbose_name='职位URL')),
                ('company_url', models.CharField(max_length=120, verbose_name='公司URL')),
                ('rep_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reptile_task.text')),
            ],
        ),
    ]
