# Generated by Django 3.2 on 2021-05-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reptile_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='requires_page',
            new_name='required_page',
        ),
    ]
